### PR TITLE
feat: ENG-63 sorts passed proposals to top on voting session results page

### PR DESCRIPTION
**Pull request by HashMapsData2Value**
- Applies a sort that compares the percentage of total votes vs required vote. Proposals that got the least amount of votes given the funds requested go to the bottom.
-  forcePass:ed proposals are also sorted to the top.
- Reorgs voteTally into a function since it is repeated twice.
- Adds wildcard * to .env in .gitignore. I kept getting `.env.testnet` files showing and I is annoying.

### CODE REVIEW

**Comment by HashMapsData2Value** [comment]
Screenshot 2023-12-07 at 18 36 39

**Comment by PhearZero** [comment]
@HashMapsData2Value , Reserve list feature can be found here:

- https://algorandfoundation.atlassian.net/browse/ENG-113

We will also want to preserve the `.env.*.templates`. `.env.template` is used by `algokit boostrap` and the testnet template is useful to mirror staging locally. The live services do not use the `.env` files

**Comment by HashMapsData2Value** [comment]
Now .env.hmd2vnet is ignored but .env.hmd2vnet.template is noticed 
Screenshot 2023-12-07 at 18 54 28

**Review by ori-shem-tov — APPROVED** [review]

**Pull request merged**
